name: Validate Spring Boot Pull Requests


on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-validate:
    name: Build and Validate Spring Boot
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout Code
        uses: actions/checkout@v3

     
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin 

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn clean install

      - name: Run Unit Tests
        run: mvn test

      - name: Run Spring Boot Application
        run: mvn spring-boot:run &
        timeout-minutes: 10

     
      - name: Integration Tests
        run: mvn verify
